### ISSUE TITLE
won't compile on Raspberry PI

### ISSUE THREAD

**Issue by steeley** [kashimAstro/ofxPixelsShape#1]
The example compiles on raspberry pi, but trying to use ofxPixelsShape in your own example
won't compile:
obj/linuxarmv6l/Release/src/main.o:(.bss+0x34): multiple definition of `_letter_'
obj/linuxarmv6l/Release/src/ofApp.o:(.bss+0x34): first defined here
obj/linuxarmv6l/Release/src/main.o:(.bss+0x28): multiple definition of `_ratio_'
obj/linuxarmv6l/Release/src/ofApp.o:(.bss+0x28): first defined here
collect2: error: ld returned 1 exit status

**Comment by kashimAstro** [comment]
@steeley theoretically it is now solved, try to re-download.

**Comment by steeley** [comment]
thanks - seems to compile ok now.
